trigger:
  branches:
    include:
    - '*'

stages:
- stage: CheckDiff
  jobs:
  - job: CheckDiffJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - task: Bash@3
      displayName: 'Fetch all branches'
      inputs:
        targetType: 'inline'
        script: |
          git config --global http.version HTTP/1.1
          git fetch --unshallow origin

    - task: Bash@3
      displayName: 'Get Current Branch Name'
      inputs:
        targetType: 'inline'
        script: |
          if [[ "$(Build.SourceBranch)" == refs/pull* ]]; then 
              echo "##vso[task.setvariable variable=branch;isOutput=true]$(echo $(Build.SourceBranch) | cut -d '/' -f 3)"
          else
              echo "##vso[task.setvariable variable=branch;isOutput=true]$(echo $(Build.SourceBranch) | cut -d '/' -f 3)"
          fi

    - task: Bash@3
      displayName: 'Check Git Diff'
      inputs:
        targetType: 'inline'
        script: |
          git diff --quiet origin/master origin/$(branch) || echo "##vso[task.setvariable variable=isDiff;isOutput=true]true"

    - script: echo $(isDiff)
      displayName: 'Print isDiff'
