trigger:
  branches:
    include:
    - '*'

stages:
- stage: CheckDiff
  jobs:
  - job: CheckDiffJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - task: Bash@3
      displayName: 'Fetch all branches and check git diff'
      inputs:
        targetType: 'inline'
        script: |
          git config --global http.version HTTP/1.1
          git fetch --unshallow origin
          
          if [[ "$(Build.SourceBranch)" == refs/pull* ]]; then 
              BRANCH=$(echo $(Build.SourceBranch) | cut -d '/' -f 3)
          else
              BRANCH=$(echo $(Build.SourceBranch) | cut -d '/' -f 3)
          fi

          git diff --quiet origin/master origin/$BRANCH
          if [ $? -eq 1 ]
          then
              echo "##vso[task.setvariable variable=isDiff;isOutput=true]true"
          fi

    - script: echo $(isDiff)
      displayName: 'Print isDiff'
